version: '3'

services:
  # mysql:
  #   image: mysql:8.0.20
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   ports:
  #     - 23306:3306
  #   environment:
  #     MYSQL_USER: 'dev_user'
  #     MYSQL_PASSWORD: 'pwd_dev_user_555'
  #     MYSQL_ROOT_PASSWORD: 'pwd_root_777'
  #     LANG: C.UTF-8
  #   volumes:
  #     - ./docker/mysql/conf.d:/etc/mysql/conf.d
  #     - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
  #     - mysql:/var/lib/mysql
  postgres:
    image: postgres:12.3-alpine
    restart: always
    ports:
      - 25432:5432
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pwd_app_555
      - POSTGRES_DB=app_db
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.0.3-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 26379:6379
    volumes:
      - redis:/data
      - ./docker/redis:/usr/local/etc/redis
volumes:
  # mysql:
  postgres:
  redis: