// Code generated by "stringer -type=Code -linecomment"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[UnknownError - -1]
	_ = x[RequestError - -2]
	_ = x[RequestParamsError - -3]
	_ = x[DatabaseError - -4]
}

const _Code_name = "数据库错误请求参数错误请求失败未知错误成功"

var _Code_index = [...]uint8{0, 15, 33, 45, 57, 63}

func (i Code) String() string {
	i -= -4
	if i < 0 || i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i+-4), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
